# Generated by Django 5.0.3 on 2024-03-20 12:23

import Petstagram.photos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_petphoto_created_at_petphoto_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petphoto',
            name='photo',
            field=models.ImageField(upload_to='pet_photos/', validators=[Petstagram.photos.models.validate_image_size_less_than_1mb]),
        ),
    ]
